language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: mudar_para_o_nome_de_sua_app_no_heroku
  api_key:
    secure: KvmY1xDJf0aDtSVSIyy0j5gaTcldl6VXYsAk2isM9zrVGZ2yY6JkrD2LX+23tR9MtSN165FO7tA9MsgQrZpPBeRwizf8EHGhuvr/vUGpZJtYguNVyqHD5poLQixCWzEown/UK5IDC3L6NKKzyLnVrGk23r0y1I71b6Ttu37W9LGcUhoDOwkj/dvkb95FZQIXyHbhca59YROZx4QefZCv/jW63WGYSqMyEVMDeinQP/TfK98YrQZofhi6xfBGPO+TXbe8Pl/FlU/8B+25wJ9JzRQBrgguieDD7LbmOn77TOGEhLtaUG9rIIzSnjX6LgIA+T3oTum99ohA4UyLiSWneU9CZHAbEN/p/1qiaX60h1v/tfjGBJooDJ1RlxU5wmT1EmsMugAWjnAY0dO1zFY55G0zKXpswnYH5WHWIVsj1B/j6FJqIOvpFOtgjGmVvNTHagfnoVcFe4/x1yTE0lop5uWt42q7N/fhBkTTbLHqLjxlok04yJ+iswdNo5z3pdg10doCrskgsbEE7I2/l8B66YZ581E/QV3jD+Sb3ryaszBWRV9m3M5yv6q4iCveoiniDqA/6XkiXqY5pVmIxzglCLTHmjRjmFsZXRtxkHg5y+Z1nDVtqHLzpE9WeayBNDEHaffNZmaUa4Sb9MLAVIE0S3JFBut82vayC+qdqXeK60c=
